### ISSUE TITLE
Criar regras de Lint

### ISSUE THREAD

**Issue by pedrovsp** [vgfocus/vgfocus-fe#5]
## Descrição:
Acho que podemos expandir as regras de Lint para cobrir regras de identação, talvez até mesmo utilizar o TSLint.

**Comment by viniciusersouza** [comment]
O TSLint é deprecado, o ideal é manter usando o ESLint mesmo.
A princípio deixei só as regras recomendadas do ESLint e a extensão JSX.

Uma coisa que a gente pode fazer é criar um `.prettierrc` pra fazer essas partes de identação, pontuação e outras regras de escrita automaticamente (format on save).

O que acha?
